export interface MediaItem {
  url: string;
  mediaType: "image" | "video";
  tags: string[];
  category: string;
}

export const MEDIA_POOL: MediaItem[] = [
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/arena/elisa-pitkanen-2w4e5wZudcM-unsplash.jpg",
    mediaType: "image",
    tags: ["training","dressage"],
    category: "arena",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/arena/malgorzata-bujalska-L0k69RU-mTI-unsplash.jpg",
    mediaType: "image",
    tags: ["training","dressage"],
    category: "arena",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/arena/pexels-chris-clark-1933184-5720457.jpg",
    mediaType: "image",
    tags: ["training","dressage"],
    category: "arena",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/arena/pexels-mark-thomas-2149938474-31548692.jpg",
    mediaType: "image",
    tags: ["training","dressage"],
    category: "arena",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/arena/pexels-mark-thomas-2149938474-31548914.jpg",
    mediaType: "image",
    tags: ["training","dressage"],
    category: "arena",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/arena/saung-digital--Bqd78mkrkQ-unsplash.jpg",
    mediaType: "image",
    tags: ["training","dressage"],
    category: "arena",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/barn/pexels-asime-2154545366-34687051.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "barn",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/barn/pexels-barbara-olsen-7882590.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "barn",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/barn/pexels-barbara-olsen-7882936.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "barn",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/barn/pexels-barbara-olsen-7883330.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "barn",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/barn/pexels-calvinseng-34301909.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "barn",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/barn/pexels-didsss-18065235.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "barn",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/barn/pexels-didsss-2333771.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "barn",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/barn/pexels-didsss-35382840.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "barn",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/barn/pexels-ezgi-gunel-2151649269-31821119.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "barn",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/barn/pexels-joel-zar-307187367-13712779%20(1).jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "barn",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/barn/pexels-joel-zar-307187367-13712779.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "barn",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/barn/pexels-joyce-dias-1262531-2401877.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "barn",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/barn/pexels-justus-menke-3490295-5213935.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "barn",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/barn/pexels-lokmansevim-9307963.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "barn",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/barn/pexels-luis-negron-260501657-12814742.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "barn",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/barn/pexels-tuba-507888946-16725788.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "barn",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-166597582-10958601.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-asemirski-13814182.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-asemirski-13814187.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-asemirski-13814188.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-asemirski-13814411.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-asemirski-13814412.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-dana-hussain-723335-1567204.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-grace-earley-3295025-5663052.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-gulsum-coban-844585548-34117614.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-gy1610-33663010.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-gy1610-34077658.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-gy1610-34317073.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-gy1610-34732248.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-italo-crespi-2169075-15551477.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-laila-klinsmann-301011-883630.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-mark-thomas-2149938474-31548692.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-mark-thomas-2149938474-31550135.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-matthiaszomer-103543.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-matthiaszomer-97587.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-mounirbarji-34691761.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-stephen-leonardi-587681991-32393600.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-stephen-leonardi-587681991-32393629.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-tainah-ferreira-2155139923-33565316.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-theotherkev-6069331.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-wendy-maxwell-22214243-6611802.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/competition/pexels-yahya-hbe-2149490834-32996824.jpg",
    mediaType: "image",
    tags: ["competition","jumping"],
    category: "competition",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/horse-portrait/pexels-didsss-2332834.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "horse-portrait",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/horse-portrait/pexels-didsss-2332836.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "horse-portrait",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/horse-portrait/pexels-efrem-efre-2786187-19036765.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "horse-portrait",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/horse-portrait/pexels-joel-zar-307187367-13712779.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "horse-portrait",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/horse-portrait/pexels-missi-kopf-12166602-6215901.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "horse-portrait",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/horse-portrait/pexels-rquiros-1848725.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "horse-portrait",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/horse-portrait/pexels-valeriiamiller-2633040.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "horse-portrait",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/horse-portrait/pexels-zahaoha-1543839.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "horse-portrait",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/sunset/pexels-arkhod-85162625-9628720.jpg",
    mediaType: "image",
    tags: ["trail-riding"],
    category: "sunset",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/sunset/pexels-baris-15028210.jpg",
    mediaType: "image",
    tags: ["trail-riding"],
    category: "sunset",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/sunset/pexels-brian-12193-60112.jpg",
    mediaType: "image",
    tags: ["trail-riding"],
    category: "sunset",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/sunset/pexels-cmrcn-27799243.jpg",
    mediaType: "image",
    tags: ["trail-riding"],
    category: "sunset",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/sunset/pexels-ericaonthego-13719519.jpg",
    mediaType: "image",
    tags: ["trail-riding"],
    category: "sunset",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/sunset/pexels-helenalopes-2009697.jpg",
    mediaType: "image",
    tags: ["trail-riding"],
    category: "sunset",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/sunset/pexels-helenalopes-2050425.jpg",
    mediaType: "image",
    tags: ["trail-riding"],
    category: "sunset",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/sunset/pexels-helenalopes-3856371.jpg",
    mediaType: "image",
    tags: ["trail-riding"],
    category: "sunset",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/sunset/pexels-helenalopes-3859349.jpg",
    mediaType: "image",
    tags: ["trail-riding"],
    category: "sunset",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/sunset/pexels-istok-u-objektivu-115344769-9981039.jpg",
    mediaType: "image",
    tags: ["trail-riding"],
    category: "sunset",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/sunset/pexels-jana-malenova-300282657-13340063.jpg",
    mediaType: "image",
    tags: ["trail-riding"],
    category: "sunset",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/sunset/pexels-jhelmuth-3211246.jpg",
    mediaType: "image",
    tags: ["trail-riding"],
    category: "sunset",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/sunset/pexels-jhelmuth-4962458.jpg",
    mediaType: "image",
    tags: ["trail-riding"],
    category: "sunset",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/sunset/pexels-mikhail-nilov-8919234.jpg",
    mediaType: "image",
    tags: ["trail-riding"],
    category: "sunset",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/sunset/pexels-missi-kopf-12166602-6215749.jpg",
    mediaType: "image",
    tags: ["trail-riding"],
    category: "sunset",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/sunset/pexels-travelerchitect-14233072.jpg",
    mediaType: "image",
    tags: ["trail-riding"],
    category: "sunset",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-113007781-9687464.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-barbara-olsen-7882376.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-barbara-olsen-7882938%20(1).jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-barbara-olsen-7882938%20(2).jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-barbara-olsen-7882938.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-barbara-olsen-7883480.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-bonnie-harder-dc-436492424-22588869.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-didsss-2332834.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-gustavo-fring-4894932.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-gy1610-34077649.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-klaudia-lorenc-569395691-16884193.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-leon-kohle-3158283-12060265.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-lokmansevim-9307966.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-markusspiske-93489.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-mehdi-faez-3475377-5878816.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-pavel-bak-22732182-6640096.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-rachel-claire-4993035.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-sergeymakashin-5368683.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-tainah-ferreira-2155139923-33565666%20(1).jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-tainah-ferreira-2155139923-33565666%20(2).jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-tainah-ferreira-2155139923-33565666.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-wsilvasjb-25461417.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  },
  {
    url: "https://sbldlebgtonaxtofflnw.supabase.co/storage/v1/object/public/post-media/bot-pool/tack/pexels-zehra-aynaci-236637804-30439649.jpg",
    mediaType: "image",
    tags: ["horse-care"],
    category: "tack",
  }
];
